test(models): mocking database for unit test (#10)
reflation/backend pull request #13
Opened 2019-11-01 14:04 UTC by BasixKOR

This PR fixes #10.

2019-11-01 15:31 UTC, BasixKOR reviewed
일부 언급이 필요할 것 같은 부분에 대해 코멘트를 남깁니다.

2019-11-01 15:31 UTC, BasixKOR commented on src/models/__mocks__/index.ts
> +    id: input.id ? input.id.toString() : cuid(),
이 라인은 `UserCreateInput`과 `User` 타입이 선택 필드를 정의하는 방법이 조금 달라 해당 부분을 맞춰주는 workaround 코드입니다. 더 좋은 방법이 있으시다면 제안 부탁드려요 😄

2019-11-01 15:31 UTC, BasixKOR commented on src/index.test.ts
> +jest.mock('./models/index')
위 코드가 있음에도 ESLint에서 __mocks__ 내 파일이 import 되지 않은 것으로 판단해 lint 중 오류를 냅니다. 향후 우회할 방법이 필요할 것으로 보입니다.

p.s. 커밋할 때에는 `--no-verify` 를 사용해 임의로 우회했습니다 😓

2019-11-02 03:35 UTC, x86chi commented on src/index.test.ts
> +jest.mock('./models/index')
임시로 문제가 나는 라인이나 파일 전체를 ignore 하면 괜찮지 않을까요?

2019-11-02 04:53 UTC, x86chi commented on src/index.test.ts
> +jest.mock('./models/index')
다시 보니 경로를`./models` 만 넣어도 될 것 같습니다.

2019-11-02 04:53 UTC, x86chi commented on src/models/__mocks__/index.ts
> +    averagePoint: 4.2,
제주대학교는 `3.5` 학점제를 사용하고 있습니다. 수정 부탁드립니다.

2019-11-02 04:53 UTC, x86chi commented on src/models/__mocks__/index.ts
> +    name: '무훈',
본래 파싱하는 데이터에선 성씨가 포함되어 있습니다. `김무훈`으로 수정 부탁드립니다.

2019-11-02 04:53 UTC, x86chi commented on src/models/__mocks__/index.ts
> +    averagePoint: input.averagePoint || 4.2,
`input.averagePoint || 3.5`로 수정 부탁드려요.

2019-11-02 04:53 UTC, x86chi commented on src/models/__mocks__/index.ts
> +export const isUserExist = async (mailid: string) =>
`user.some` 메서드는 `Promise` 를 반환하지 않습니다. `async` 를 빼주세요.

2019-11-02 04:53 UTC, x86chi commented on src/models/__mocks__/index.ts
> +    id: input.id ? input.id.toString() : cuid(),
cuid를 서버 파트에 부담하고, `UserCreateInput`에 ID를 빼셔도 괜찮을 것 같습니다.

2019-11-02 05:12 UTC, mu-hun requested changes
수정 요청 사안에 납득하신다면 제가 커밋을 해도 괜찮을까요?

2019-11-02 05:12 UTC, x86chi commented on src/models/__mocks__/index.ts
> +export const createUser = async (input: UserCreateInput): Promise<User> => {
`await` 를 쓰는 구문이 없지만 [`src/checkVaild.ts#L34`](https://github.com/reflation/backend/blob/master/src/checkVaild.ts#L34)와의 호완성을 위해 놓아두는 것이 나을까요?

2019-11-02 05:15 UTC, x86chi commented on src/models/__mocks__/index.ts
> +  },
다음 PR 작업 이전에 `semesters` 스키마를 User Type 에 적용해두면 좋겠네요.

2019-11-02 05:39 UTC, x86chi commented
PS: `index.test.ts` [업데이트를 제안드립니다](https://gist.github.com/x86chi/f22e8be0eb351540a20506552a7c004b)

수신 받은 body의 타입을 TypeUser과 비교하여([45줄 참고](https://gist.github.com/x86chi/f22e8be0eb351540a20506552a7c004b#file-index-test-ts-L45)) 체크할 좋은 방법이 있을까요?

2019-11-02 05:43 UTC, mu-hun requested changes

2019-11-02 05:43 UTC, x86chi commented on src/models/__mocks__/index.ts
> +  return users[foundIndex]
```ts
  averagePoint,
}: TypeUser): Promise<User> => {
  const foundIndex = users.findIndex(user => user.mailid === mailid)
  users[foundIndex].averagePoint = averagePoint || 3.5
  return users[foundIndex]
}
```

`data`는 `TypeUser`에 없는 속성입니다.

2019-11-02 09:29 UTC, BasixKOR commented on src/models/__mocks__/index.ts
> +    id: input.id ? input.id.toString() : cuid(),
UserCreateInput은 Prisma 제공 타입이라 id를 빼는 건 어려울 것 같고, Prisma에서 id가 제공될 때 어떻게 작동하는지 잠깐 살펴보고 비슷하게 적용해볼게요

2019-11-02 09:29 UTC, BasixKOR commented on src/models/__mocks__/index.ts
> +    name: '무훈',
수정하겠습니다.

2019-11-02 09:30 UTC, BasixKOR commented on src/models/__mocks__/index.ts
> +export const isUserExist = async (mailid: string) =>
Promise.resolve로 감싸야겠네요 😂

2019-11-02 09:31 UTC, BasixKOR commented on src/models/__mocks__/index.ts
> +export const createUser = async (input: UserCreateInput): Promise<User> => {
Mocking하는 createUser가 Promise를 반환하므로 똑같이 작동하도록 구성했습니다.

2019-11-02 11:22 UTC, x86chi commented on src/models/__mocks__/index.ts
> +export const createUser = async (input: UserCreateInput): Promise<User> => {
https://github.com/reflation/backend/pull/13#discussion_r341804809 답글과 동일하게 Promise.resolve 를 쓰겠습니다.

2019-11-02 11:38 UTC, x86chi commented
현재 피드백을 준 부분에 대한 커밋을 작업하고 있습니다.

2019-11-02 12:43 UTC, x86chi commented on src/index.test.ts
> +jest.mock('./models/index')
tsconfig의 include 속성에 해당 파일의 경로를 집어넣으니 해결되었습니다.

2019-11-03 11:05 UTC, mu-hun approved these changes

2019-11-03 12:12 UTC, merged