chore: '/fetch' route send empty body
reflation/backend pull request #18
Opened 2019-11-08 13:08 UTC by x86chi

오직 `/load` 에서만 데이터를 받아 올 수 있습니다. 단일 책임을 따르자면 이게 더 나을 것 같네요.

## 오류?

https://github.com/reflation/backend/blob/dcbfaedf1793e58a732e8226bc52b9a75e383a02/src/index.test.ts#L52-L54

`except` 두번째 인자로 done을 집어넣는 경우 500 코드를 반환하고 있습니다.

2019-11-08 13:16 UTC, BasixKOR commented
500 오류 반환에 대해서만 확인해본 후 자세히 리뷰할게요~

2019-11-08 15:27 UTC, BasixKOR requested changes

2019-11-08 15:27 UTC, BasixKOR commented on src/index.test.ts
>          .expect(201)
테스트 케이스 설명은 return 401 status인데 실제로는 201 status를 expect하고 있는 것으로 보입니다.

2019-11-08 15:27 UTC, BasixKOR commented on src/index.test.ts
>          }))
제 PC에서 확인해 본 결과 expect와 end를 따로 작성하는 경우 status 코드가 expect된 값과 달라도 무시되는 것으로 보입니다 😱 `expect(201, done)` 꼴로 고치고 어떤 부분에서 500 에러가 나는 지 확인해보는 편이 좋을 것으로 보입니다.

2019-11-09 01:17 UTC, x86chi commented on src/index.test.ts
>          }))
세상에 저도 좀 더 찾아보겠습니다.

2019-11-09 01:55 UTC, x86chi commented on src/index.test.ts
>          .expect(201)
넵 401로 명시해둬야 됩니다. #15 에서 놓친 것 같네요.

2019-11-09 01:58 UTC, x86chi commented on src/index.test.ts
>          }))
`e.message` 가 `undefined`를 반환하고 있어서 생기는 문제네요 😅 지금 그래서 `fetchAndParse` 내부 예외 처리를 검토하고 있습니다.

https://github.com/reflation/backend/blob/a66948987500067482df08d5b12881865ff386b0/src/routes.ts#L54-L57

2019-11-09 07:13 UTC, x86chi commented on src/utils/fetch.ts
> +        const cookie = headers['set-cookie']!
왜 그러는지 모르겠으나 쿠키 정보가 비어 있는 상황입니다.

2019-11-09 10:14 UTC, x86chi commented on src/utils/fetch.ts
> +        const cookie = headers['set-cookie']!
수동 E2E 테스트와 `yarn demo` 로는 문제 없이 돌아갑니다. 단위 테스트 코드에 문제가 있는 것 같네요.

2019-11-09 14:18 UTC, x86chi commented on src/index.test.ts
> +    //     .expect(201, done))
> ~~좀 신경 쓰이지만 도구는 도구일 뿐~~ 실제 환경에서 문제가 없다면 지나치게 집착하지 맙시다.

@BasixKOR 괜찮은지 의견을 여쭤보고 싶네요~

2019-11-09 14:21 UTC, BasixKOR commented on src/index.test.ts
> +    //     .expect(201, done))
그러면 일단 이 부분은 이슈로 분리 등록해두고 이후에 해결하는 편이 나을 것 같네요 :smile:

2019-11-09 14:30 UTC, x86chi commented on src/utils/fetch.ts
> +        const cookie = headers['set-cookie']!
해당 문제를 #19로 이전합니다.

2019-11-09 14:30 UTC, x86chi commented on src/index.test.ts
> +    //     .expect(201, done))
👌

2019-11-09 14:38 UTC, merged